import type { AccountProfile, CoffeeMachineUpgradeId, RoleExperienceAward, ShopUpgradeId } from "../core/v2-types";
import type { ShopTabId } from "./v2-render-shop-panel";

export type PlayTabId = "events" | "workstation" | "relationship" | "shop" | "research" | "talent" | "settings";
export type RoleRailViewId = "achievements" | "messages" | "announcements";
export type TalentPanelTabId = "character" | "relation" | "equip" | "growth" | "publication";
export type ShopUpgradeNoticeTab = Extract<ShopTabId, "ai" | "coffee">;
export type ResearchSortMode = "year" | "citations";
export type ResearchAuthorshipFilter = "all" | "first" | "coauthor";
export interface PlayRenderUiState {
  activeRoleRailView?: RoleRailViewId;
  announcementPageIndex?: number;
  talentTreePageIndex?: number;
  talentTreeSelectedNodeByPage?: readonly number[];
  isFeedbackOpen?: boolean;
  dateDisplayMode?: AccountProfile["dateDisplayMode"];
  roleExperienceAward?: RoleExperienceAward;
  activePlayTab?: PlayTabId;
  helpPageByContext?: Readonly<Record<string, number>>;
  isHelpOpen?: boolean;
  isEventContentOpen?: boolean;
  isEndingContentOpen?: boolean;
  activeEventId?: string | null;
  activeEventHistoryId?: string | null;
  activeEventHistoryIndex?: number | null;
  activeLogPage?: number | null;
  activePendingPage?: number | null;
  activeRelationshipIndex?: number | null;
  activeShopTab?: ShopTabId;
  showShopUpgradeNotice?: boolean;
  shopUpgradeNoticeTabs?: readonly ShopUpgradeNoticeTab[];
  selectedChairUpgradeId?: ShopUpgradeId | null;
  selectedCoffeeUpgradeId?: Exclude<CoffeeMachineUpgradeId, null> | null;
  activeTalentTab?: TalentPanelTabId;
  advisorSalaryStartIndex?: number | null;
  loverRewardPage?: number;
  internshipPage?: number;
  gameGrowthPage?: number;
  currentResearchPaperIndex?: number | null;
  researchSortMode?: ResearchSortMode;
  researchAuthorshipFilter?: ResearchAuthorshipFilter;
}
