export const DEBUG_STAT_IDS = ["san", "research", "social", "favor", "money"] as const;
export type DebugStatId = typeof DEBUG_STAT_IDS[number];

export const GAME_ACTION_IDS = [
  "start-game",
  "restart-game",
  "reset-game",
  "select-role",
  "change-lobby-role-page",
  "change-role-achievement-page",
  "set-date-display-mode",
  "select-paper",
  "create-paper",
  "reroll-paper-topic",
  "discard-paper",
  "research-paper",
  "submit-paper",
  "submit-journal-paper",
  "withdraw-paper",
  "promote-paper",
  "read-paper",
  "part-time-work",
  "rest",
  "resolve-event",
  "debug-adjust-stat",
  "debug-add-paper",
  "debug-shift-month",
  "debug-trigger-event",
  "debug-add-all-buffs",
  "next-month",
  "force-next-month",
  "buy-shop-item",
  "sell-shop-item",
  "upgrade-shop-item",
  "buy-coffee",
  "buy-coffee-machine",
  "sell-coffee-machine",
  "upgrade-coffee-machine",
  "toggle-coffee-subscription",
  "buy-ai-month",
  "toggle-ai-subscription",
  "buy-support-item",
  "sell-support-item",
] as const;
export type GameActionId = typeof GAME_ACTION_IDS[number];
