import type { AdvisorDefinition, AdvisorRequirements, PaperTarget, RoleBaseId, RoleDefinition, RoleId } from "./v2-types";

export const MASTER_TOTAL_MONTHS = 34;
export const PHD_TOTAL_MONTHS = 58;
export const MAX_ACTIONS_PER_MONTH = 2;
export const PAPER_SLOT_LIMIT = 4;
export const PAPER_READY_THRESHOLD = 4;
export const MAX_SAN = 20;
export const MAX_LOG_ENTRIES = 24;

export const ROLE_BASE_ORDER: RoleBaseId[] = ["normal", "genius", "social", "rich", "teacher-child", "chosen"];
export const ROLE_ORDER: RoleId[] = [
  "normal",
  "genius",
  "social",
  "rich",
  "teacher-child",
  "chosen",
  "rewinder",
  "research-captain",
  "normal-reversed",
  "genius-reversed",
  "social-reversed",
  "rich-reversed",
  "teacher-child-reversed",
  "chosen-reversed",
];
export const ROLE_DEFINITIONS: RoleDefinition[] = [
  {
    id: "normal",
    baseId: "normal",
    mode: "upright",
    name: "大多数",
    shortName: "大多数",
    icon: "👤",
    tagline: "芸芸众生中的普通一员",
    description: "无特殊能力",
    bonus: "无特殊能力",
    awakenIcon: "🔥",
    awakenName: "我命由我不由天",
    awakenDesc: "转博时所有属性×2，之后属性溢出时上限+1",
    hiddenAwakenName: "勤能补拙",
    hiddenAwakenIcon: "💪",
    hiddenAwakenDesc: "每个月行动次数+1（看论文、写论文、想idea、打工、做实验可以做2次）",
    startingStats: { san: 20, research: 1, social: 1, favor: 1, money: 1 },
  },
  {
    id: "genius",
    baseId: "genius",
    mode: "upright",
    name: "院士转世",
    shortName: "院士",
    icon: "🔬",
    tagline: "天生就是做科研的料",
    description: "初始科研能力+5，每年+1",
    bonus: "初始科研能力+5，每年+1",
    awakenIcon: "🧬",
    awakenName: "学术天赋觉醒",
    awakenDesc: "转博时每有1篇A类论文，科研+2，上限+4（3篇B类折算1篇A类）",
    hiddenAwakenName: "预见未来热点",
    hiddenAwakenIcon: "🔮",
    hiddenAwakenDesc: "论文的idea和实验分数每月不再衰减",
    startingStats: { san: 20, research: 1, social: 1, favor: 1, money: 1 },
  },
  {
    id: "social",
    baseId: "social",
    mode: "upright",
    name: "社交达人",
    shortName: "社交",
    icon: "🤝",
    tagline: "八面玲珑的社交高手",
    description: "初始社交能力+5，每年+1",
    bonus: "初始社交能力+5，每年+1",
    awakenIcon: "🌐",
    awakenName: "人脉网络激活",
    awakenDesc: "转博时每认识过一人社交+1且上限+1，根据社交能力改变审稿人分布",
    hiddenAwakenName: "同学救我",
    hiddenAwakenIcon: "🆘",
    hiddenAwakenDesc: "社交变为6且获得主动技能（限用3次，之后每次使用社交-1）：下次生产论文时，科研能力视为科研+社交",
    startingStats: { san: 20, research: 1, social: 1, favor: 1, money: 1 },
  },
  {
    id: "rich",
    baseId: "rich",
    mode: "upright",
    name: "富可敌国",
    shortName: "富豪",
    icon: "💰",
    tagline: "家境殷实无忧无虑",
    description: "金币值初始+8，寒假压岁钱+4",
    bonus: "金币值初始+8，寒假压岁钱+4",
    awakenIcon: "💎",
    awakenName: "财富倍增术",
    awakenDesc: "转博时金币×3",
    hiddenAwakenName: "白手起家术",
    hiddenAwakenIcon: "🏦",
    hiddenAwakenDesc: "后续打工、实习的金钱收入翻倍",
    startingStats: { san: 20, research: 1, social: 1, favor: 1, money: 1 },
  },
  {
    id: "teacher-child",
    baseId: "teacher-child",
    mode: "upright",
    name: "导师子女",
    shortName: "子女",
    icon: "👨‍👧",
    tagline: "近水楼台先得月",
    description: "初始导师好感度+5，每年+1",
    bonus: "初始导师好感度+5，每年+1",
    awakenIcon: "👑",
    awakenName: "血脉共鸣",
    awakenDesc: "每6好感度赠送1篇C类论文，每月自动和导师交流一次",
    hiddenAwakenName: "导师救我",
    hiddenAwakenIcon: "🛡️",
    hiddenAwakenDesc: "好感度变为6且获得主动技能（限用3次，之后每次使用好感度-1）：下次生产论文时，科研能力视为科研+好感度",
    startingStats: { san: 20, research: 1, social: 1, favor: 1, money: 1 },
  },
  {
    id: "chosen",
    baseId: "chosen",
    mode: "upright",
    name: "天选之人",
    shortName: "天选",
    icon: "⭐",
    tagline: "命运的宠儿全面发展",
    description: "初始科研/社交/好感/金币+2，每2年+1",
    bonus: "初始科研/社交/好感/金币+2，每2年+1",
    awakenIcon: "✨",
    awakenName: "查缺补漏",
    awakenDesc: "转博时补齐所有短板",
    hiddenAwakenName: "孤注一掷",
    hiddenAwakenIcon: "🎯",
    hiddenAwakenDesc: "选择一项属性，其他两项变为1并将值转化到该属性",
    startingStats: { san: 20, research: 1, social: 1, favor: 1, money: 1 },
  },
  {
    id: "rewinder",
    baseId: "rewinder",
    mode: "upright",
    name: "轮回者",
    shortName: "轮回",
    icon: "⏳",
    tagline: "把每个阶段都重新推演到极致的人",
    description: "特殊角色展示中，正式机制待定",
    bonus: "特殊角色展示中，正式机制待定",
    awakenIcon: "🕰️",
    awakenName: "时间回路",
    awakenDesc: "特殊角色展示中，正式机制待定",
    startingStats: { san: 20, research: 1, social: 1, favor: 1, money: 1 },
  },
  {
    id: "research-captain",
    baseId: "research-captain",
    mode: "upright",
    name: "统御者",
    shortName: "统御",
    icon: "🧭",
    tagline: "把不同人拉成最强科研阵列的人",
    description: "特殊角色展示中，正式机制待定",
    bonus: "特殊角色展示中，正式机制待定",
    awakenIcon: "🚩",
    awakenName: "编队统筹",
    awakenDesc: "特殊角色展示中，正式机制待定",
    startingStats: { san: 20, research: 1, social: 1, favor: 1, money: 1 },
  },
  {
    id: "normal-reversed",
    baseId: "normal",
    mode: "reversed",
    name: "怠惰·大多数",
    shortName: "怠惰",
    icon: "😴",
    tagline: "懒惰是原罪，也是护盾",
    description: "SAN减少翻倍，初始属性全5，每月SAN+3",
    bonus: "SAN减少翻倍，初始属性全5，每月SAN+3",
    awakenIcon: "💀",
    awakenName: "极致怠惰",
    awakenDesc: "转博时属性翻倍，SAN上限+50%。SAN减少3倍，每月SAN+已损SAN的10%",
    startingStats: { san: 20, research: 1, social: 1, favor: 1, money: 1 },
  },
  {
    id: "genius-reversed",
    baseId: "genius",
    mode: "reversed",
    name: "愚钝·院士转世",
    shortName: "愚钝",
    icon: "🤡",
    tagline: "科研是什么？能吃吗？",
    description: "科研固定0，全论文槽，科研提升→金/SAN+4，社交/好感+1",
    bonus: "科研固定0，全论文槽，科研提升→金/SAN+4，社交/好感+1",
    awakenIcon: "🎭",
    awakenName: "大智若愚",
    awakenDesc: "科研提升→金/SAN+4，社交/好感+1，（社交/好感/SAN）上限+1",
    initialPaperSlots: 4,
    startingStats: { san: 20, research: 1, social: 1, favor: 1, money: 1 },
  },
  {
    id: "social-reversed",
    baseId: "social",
    mode: "reversed",
    name: "嫉妒·社交达人",
    shortName: "嫉妒",
    icon: "🐍",
    tagline: "见不得别人好，也见不得自己差",
    description: "社交初始5，社交-1→科研/好感+1 | 社交+1→SAN/金+1",
    bonus: "社交初始5，社交-1→科研/好感+1 | 社交+1→SAN/金+1",
    awakenIcon: "👁️",
    awakenName: "嫉妒升级",
    awakenDesc: "关系栏换人（科研/好感/SAN）上限+3",
    startingStats: { san: 20, research: 1, social: 1, favor: 1, money: 1 },
  },
  {
    id: "rich-reversed",
    baseId: "rich",
    mode: "reversed",
    name: "贪求·富可敌国",
    shortName: "贪求",
    icon: "🏴‍☠️",
    tagline: "除了钱一无所有",
    description: "每月SAN/属性重置为1，重置的属性变化转为金钱，每月金钱+3",
    bonus: "每月SAN/属性重置为1，重置的属性变化转为金钱，每月金钱+3",
    awakenIcon: "💸",
    awakenName: "金钱的力量",
    awakenDesc: "每月SAN重置为1，属性降低20%，属性变化转为金钱，每花费6金币SAN/属性+1，每月金钱+5%",
    startingStats: { san: 20, research: 1, social: 1, favor: 1, money: 1 },
  },
  {
    id: "teacher-child-reversed",
    baseId: "teacher-child",
    mode: "reversed",
    name: "玩世·导师子女",
    shortName: "玩世",
    icon: "🎪",
    tagline: "叛逆是我的代名词",
    description: "好感不会低于0，好感归0→重置为6，社交/科研+1，金币补足到3",
    bonus: "好感不会低于0，好感归0→重置为6，社交/科研+1，金币补足到3",
    awakenIcon: "🃏",
    awakenName: "变本加厉",
    awakenDesc: "好感归0→重置为4，金币补足到5，轮流触发社交/科研/社交上限/科研上限+1",
    startingStats: { san: 20, research: 1, social: 1, favor: 1, money: 1 },
  },
  {
    id: "chosen-reversed",
    baseId: "chosen",
    mode: "reversed",
    name: "空想·天选之人",
    shortName: "空想",
    icon: "🌀",
    tagline: "命运是一场轮盘赌",
    description: "每月:科研/社交/好感随机交换，SAN/金随机交换，可突破属性上限",
    bonus: "每月:科研/社交/好感随机交换，SAN/金随机交换，可突破属性上限",
    awakenIcon: "🎲",
    awakenName: "命运轮盘",
    awakenDesc: "每月:科研/社交/好感/SAN/金全部随机交换，可突破属性上限",
    startingStats: { san: 20, research: 1, social: 1, favor: 1, money: 1 },
  },
];

export const ADVISOR_DEFINITIONS: AdvisorDefinition[] = [
  { id: "chen-ming", name: "陈明", color: "#b8860b" },
  { id: "zhou-lan", name: "周岚", color: "#e67e22" },
  { id: "lin-hao", name: "林浩", color: "#3498db" },
  { id: "zhao-ning", name: "赵宁", color: "#2ecc71" },
];

export const ADVISOR_REQUIREMENTS: AdvisorRequirements = {
  phdYear2: 2,
  phdYear3: 3,
  masterGrad: 1,
  phdGrad: 7,
};

export const ADVISOR_SALARY = { master: 1, phd: 3 } as const;

export const SCORE_BY_TARGET: Record<PaperTarget, number> = { C: 1, B: 2, A: 4 };
export const REVIEW_MONTHS_BY_TARGET: Record<PaperTarget, number> = { C: 4, B: 4, A: 4 };
export const ACCEPT_THRESHOLD_BY_TARGET: Record<PaperTarget, number> = { C: 10, B: 18, A: 26 };
export const SUBMIT_READY_THRESHOLD_BY_TARGET: Record<PaperTarget, number> = { C: 6, B: 12, A: 18 };
export const PAPER_SLOT_RESEARCH_THRESHOLDS = [0, 6, 12, 18] as const;
export const NATURE_SUBMISSION_THRESHOLD = 150;
export const NATURE_SUBMISSION_SUB_THRESHOLD = 100;
export const NATURE_ACCEPT_THRESHOLD = 500;
export const NATURE_ACCEPT_SUB_THRESHOLD = 250;
