import type { AdvisorRequirements, PaperTarget, RoleDefinition } from "./v2-types";

export const MASTER_TOTAL_MONTHS = 68;
export const PHD_TOTAL_MONTHS = 68;
export const PAPER_SLOT_LIMIT = 4;
export const MAX_SAN = 20;

export const ROLE_DEFINITIONS: RoleDefinition[] = [
  {
    id: "normal",
    mode: "upright",
    gender: "male",
    name: "大多数",
    icon: "👤",
    bonus: "无特殊能力",
    awakenIcon: "🔥",
    awakenName: "我命由我不由天",
    awakenDesc: "转博时所有属性×2，之后属性溢出时上限+1",
    hiddenAwakenName: "勤能补拙",
    hiddenAwakenIcon: "💪",
    hiddenAwakenDesc: "每个月行动次数+1（看论文、写论文、想idea、打工、做实验可以做2次）",
    startingStats: { san: 20, research: 1, social: 1, favor: 1, money: 1 },
  },
  {
    id: "genius",
    mode: "upright",
    gender: "male",
    name: "院士转世",
    icon: "🔬",
    bonus: "初始科研能力+5，每年+1",
    awakenIcon: "🧬",
    awakenName: "学术天赋觉醒",
    awakenDesc: "转博时每有1篇A类论文，科研+2，上限+4（3篇B类折算1篇A类）",
    hiddenAwakenName: "预见未来热点",
    hiddenAwakenIcon: "🔮",
    hiddenAwakenDesc: "论文的三项分数每月不再衰减",
    startingStats: { san: 20, research: 6, social: 1, favor: 1, money: 1 },
  },
  {
    id: "social",
    mode: "upright",
    gender: "male",
    name: "社交达人",
    icon: "🤝",
    bonus: "初始社交能力+5，每年+1",
    awakenIcon: "🌐",
    awakenName: "人脉网络激活",
    awakenDesc: "转博时每认识过一人，社交+1且上限+1；审稿人分布随社交能力变化",
    hiddenAwakenName: "同学救我",
    hiddenAwakenIcon: "🆘",
    hiddenAwakenDesc: "社交变为6且获得主动技能（限用3次，之后每次使用社交-1）：下次产出论文时，科研能力视为科研+社交",
    startingStats: { san: 20, research: 1, social: 6, favor: 1, money: 1 },
  },
  {
    id: "rich",
    mode: "upright",
    gender: "female",
    name: "富可敌国",
    icon: "💰",
    bonus: "金币初始+8，寒假可收到额外压岁钱",
    awakenIcon: "💎",
    awakenName: "财富倍增术",
    awakenDesc: "转博时金币×3",
    hiddenAwakenName: "白手起家术",
    hiddenAwakenIcon: "🏦",
    hiddenAwakenDesc: "后续打工、实习的金币收入翻倍",
    startingStats: { san: 20, research: 1, social: 1, favor: 1, money: 9 },
  },
  {
    id: "teacher-child",
    mode: "upright",
    gender: "female",
    name: "导师子女",
    icon: "👨‍👧",
    bonus: "初始导师好感 +5，每年 +1",
    awakenIcon: "👑",
    awakenName: "血脉共鸣",
    awakenDesc: "每6好感获赠1篇C类论文，每月自动和导师交流一次",
    hiddenAwakenName: "导师救我",
    hiddenAwakenIcon: "🛡️",
    hiddenAwakenDesc: "好感变为6且获得主动技能（限用3次，之后每次使用好感-1）：下次产出论文时，科研能力视为科研+好感",
    startingStats: { san: 20, research: 1, social: 1, favor: 6, money: 1 },
  },
  {
    id: "chosen",
    mode: "upright",
    gender: "female",
    name: "天选之人",
    icon: "⭐",
    bonus: "初始科研/社交/好感/金币+2，每2年+1",
    awakenIcon: "✨",
    awakenName: "查缺补漏",
    awakenDesc: "转博时补齐所有短板",
    hiddenAwakenName: "孤注一掷",
    hiddenAwakenIcon: "🎯",
    hiddenAwakenDesc: "选择一项属性，其他两项变为1并将值转化到该属性",
    startingStats: { san: 20, research: 3, social: 3, favor: 3, money: 3 },
  },
  {
    id: "rewinder",
    mode: "upright",
    gender: "female",
    name: "轮回者",
    icon: "⏳",
    bonus: "特殊角色展示中，正式机制待定",
    awakenIcon: "🕰️",
    awakenName: "时间回路",
    awakenDesc: "特殊角色展示中，正式机制待定",
    startingStats: { san: 20, research: 1, social: 1, favor: 1, money: 1 },
  },
  {
    id: "research-captain",
    mode: "upright",
    gender: "male",
    name: "统御者",
    icon: "🧭",
    bonus: "特殊角色展示中，正式机制待定",
    awakenIcon: "🚩",
    awakenName: "编队统筹",
    awakenDesc: "特殊角色展示中，正式机制待定",
    startingStats: { san: 20, research: 1, social: 1, favor: 1, money: 1 },
  },
  {
    id: "normal-reversed",
    mode: "reversed",
    gender: "male",
    name: "怠惰·大多数",
    icon: "😴",
    bonus: "SAN减少翻倍，初始属性全5，每月SAN+3",
    awakenIcon: "💀",
    awakenName: "极致怠惰",
    awakenDesc: "转博时属性翻倍，SAN上限+50%。SAN减少3倍，每月SAN+已损SAN的10%",
    startingStats: { san: 20, research: 1, social: 1, favor: 1, money: 1 },
  },
  {
    id: "genius-reversed",
    mode: "reversed",
    gender: "male",
    name: "愚钝·院士转世",
    icon: "🤡",
    bonus: "科研固定0，全论文槽，科研提升→金/SAN+4，社交/好感+1",
    awakenIcon: "🎭",
    awakenName: "大智若愚",
    awakenDesc: "科研提升→金/SAN+4，社交/好感+1，（社交/好感/SAN）上限+1",
    initialPaperSlots: 4,
    startingStats: { san: 20, research: 1, social: 1, favor: 1, money: 1 },
  },
  {
    id: "social-reversed",
    mode: "reversed",
    gender: "male",
    name: "嫉妒·社交达人",
    icon: "🐍",
    bonus: "社交初始5，社交-1→科研/好感+1 | 社交+1→SAN/金+1",
    awakenIcon: "👁️",
    awakenName: "嫉妒升级",
    awakenDesc: "关系栏换人（科研/好感/SAN）上限+3",
    startingStats: { san: 20, research: 1, social: 1, favor: 1, money: 1 },
  },
  {
    id: "rich-reversed",
    mode: "reversed",
    gender: "female",
    name: "贪求·富可敌国",
    icon: "🏴‍☠️",
    bonus: "每月 SAN/属性重置为 1，重置的属性变化转为金币，每月金币 +3",
    awakenIcon: "💸",
    awakenName: "金币的力量",
    awakenDesc: "每月 SAN 重置为 1，属性降低 20%，属性变化转为金币，每花费 6 金币 SAN/属性 +1，每月金币 +5%",
    startingStats: { san: 20, research: 1, social: 1, favor: 1, money: 1 },
  },
  {
    id: "teacher-child-reversed",
    mode: "reversed",
    gender: "female",
    name: "玩世·导师子女",
    icon: "🎪",
    bonus: "好感不会低于0，好感归0→重置为6，社交/科研+1，金币补足到3",
    awakenIcon: "🃏",
    awakenName: "变本加厉",
    awakenDesc: "好感归0→重置为4，金币补足到5，轮流触发社交/科研/社交上限/科研上限+1",
    startingStats: { san: 20, research: 1, social: 1, favor: 1, money: 1 },
  },
  {
    id: "chosen-reversed",
    mode: "reversed",
    gender: "female",
    name: "空想·天选之人",
    icon: "🌀",
    bonus: "每月:科研/社交/好感随机交换，SAN/金随机交换，可突破属性上限",
    awakenIcon: "🎲",
    awakenName: "命运轮盘",
    awakenDesc: "每月:科研/社交/好感/SAN/金全部随机交换，可突破属性上限",
    startingStats: { san: 20, research: 1, social: 1, favor: 1, money: 1 },
  },
];

export const ADVISOR_REQUIREMENTS: AdvisorRequirements = {
  phdYear2: 2,
  phdYear3: 3,
  masterGrad: 1,
  phdGrad: 7,
};

export const ADVISOR_SALARY = { master: 1, phd: 3 } as const;

export const SCORE_BY_TARGET: Record<PaperTarget, number> = { C: 1, B: 2, A: 4 };
export const PAPER_SLOT_RESEARCH_THRESHOLDS = [0, 6, 12, 18] as const;
